# Generated by Django 5.2.11 on 2026-04-07 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_book_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(default='No Author', max_length=200)),
                ('ingredients', models.CharField(max_length=200)),
                ('nr_ingredients', models.IntegerField(default=0)),
                ('time_minutes', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
